name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r birthdaySchedule/requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Zip the the python file
    - uses: actions/checkout@v3
    - name: Zip the birthdaySignup python file
      run: |
        cd birthdaySignup && zip -r ../insertBirthdayRecord.zip handler.py && cd ../ && ls -ls *.zip
    - name: Zip the birthdaySchedule python file
      run: |
        cd birthdaySchedule && zip -r ../birthdaySchedule.zip handler.py && cd ../ && ls -ls *.zip
    - name: Update Birthday Lambda Functions
      run: |
        aws lambda update-function-code \
          --function-name  arn:aws:lambda:us-west-2:806320764941:function:insertBirthdayRecord \
          --zip-file fileb://insertBirthdayRecord.zip && \
        aws lambda update-function-code \
          --function-name  arn:aws:lambda:us-west-2:806320764941:function:barSchedule \
          --zip-file fileb://birthdaySchedule.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'
